name: 步步宝

on:
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【步步宝】"
              if: env.DKDURL
              run: |
                  node Task/dkd.js
              env:
                  DKDURL: ${{ secrets.DKDURL }}
                  DKDHD: ${{ secrets.DKDHD }}
                  DKDBODY: ${{ secrets.DKDBODY }}
