# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: dkd多看点视频

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1,6 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      Dkdhd: ${{ secrets.DKD_HD }}
      Dkdbody: ${{ secrets.DKD_BD }}
      Dkdvd_body: ${{ secrets.DKD_VBD }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【多看点- 视频】'
        if: env.DKD_VBD         
        run: |
          cd ~/Scripts
          node Task/dkdsp.js
        env:
          DKD_HD: ${{ secrets.DKD_HD }}
          DKD_BD: ${{ secrets.DKD_BD }}
          DKD_VBD: ${{ secrets.DKD_VBD }}
      
  
      #- name: '运行 【dkd视频2】'
      #  if: env.Dkdvd_body2         
      #  run: |
      #    cd ~/Scripts
      #    node Task/dkdsp.js
      #  env:
      #    Dkdhd: ${{ secrets.Dkdhd }}
      #    Dkdbody: ${{ secrets.Dkdbody }}
      #    Dkdvd_body: ${{ secrets.Dkdvd_body2 }}
          


