 name: 笑谱1+2

 on:
   workflow_dispatch:
   schedule:
     - cron: '*/30 0-15 * * *'
   watch:
     types: started
   repository_dispatch:
     types: _

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     env:
         XP_REFRESHTOKEN_1_2 : ${{ secrets.XP_REFRESHTOKEN_1_2 }}
         XP_live: ${{ secrets.XP_live }}
         XP_CASH: ${{ secrets.XP_CASH }}
     steps:
       - name: Checkout
         run: |
           git clone https://github.com/ziye66666/JavaScript.git ~/JavaScript
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         if: env.XP_REFRESHTOKEN_1_2
         run: |
           cd ~/JavaScript
           npm install
       - name: '运行 【笑谱】'
         if: env.XP_REFRESHTOKEN_1_2
         run: |
           cd ~/JavaScript
           node Task/iboxpay_1_2.js
         env:
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
