name: 笑谱

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '*/30 0-15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/GGitJID/YangMao.git ~/YangMao
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/YangMao
          npm install
          npm install cron
          npm install request
      - name: '运行 【笑谱】'
        run: |
          cd ~/YangMao   
          node Task/iboxpays.js